export const INITIAL_CLUBS = [
  {
    id: 'c1',
    clubtitle: 'OWASP Student Chapter PCCOE',
    clubusername: 'owasp',
    category: 'Technical',
    description: 'Open Web Application Security Project - Leading cybersecurity and application security community at PCCOE.',
    logo: '/owasp_rulccu.png',
    coverImage: '/b1_moeeg9.png',
    membersCount: 420,
    followersCount: 1250,
    lead: 'Chirag Ferwani',
    email: 'owasp@pccoepune.org',
    socials: { instagram: 'owasp_pccoe', linkedin: 'owasp-pccoe', github: 'owasp-pccoe' },
    isJoined: true,
  },
  {
    id: 'c2',
    clubtitle: 'GDGC PCCOE',
    clubusername: 'gdgc',
    category: 'Technical',
    description: 'Google Developer Groups on Campus - Empowering developers through Google technologies, AI, Android, and Cloud.',
    logo: '/gdgc_euo0ky.png',
    coverImage: '/b2_bh32na.png',
    membersCount: 560,
    followersCount: 1890,
    lead: 'Yashvardhan Borude',
    email: 'gdgc@pccoepune.org',
    socials: { instagram: 'gdgc_pccoe', linkedin: 'gdgc-pccoe', github: 'gdgc-pccoe' },
    isJoined: true,
  },
  {
    id: 'c3',
    clubtitle: 'ACM Student Chapter',
    clubusername: 'acm',
    category: 'Technical',
    description: 'Association for Computing Machinery - Dedicated to advancing computing as a science & profession.',
    logo: '/acm_dhgbaa.png',
    coverImage: '/b3_z2ueqz.png',
    membersCount: 380,
    followersCount: 940,
    lead: 'Aditya Sharma',
    email: 'acm@pccoepune.org',
    socials: { instagram: 'acm_pccoe', linkedin: 'acm-pccoe', github: 'acm-pccoe' },
    isJoined: false,
  },
  {
    id: 'c4',
    clubtitle: 'GeeksforGeeks PCCOE',
    clubusername: 'gfg',
    category: 'Technical',
    description: 'GFG Student Chapter - Competitive programming, DSA masterclasses, and placement preparation.',
    logo: '/gfg_kqw753.png',
    coverImage: '/b4_kbdsrp.png',
    membersCount: 490,
    followersCount: 1420,
    lead: 'Neha Joshi',
    email: 'gfg@pccoepune.org',
    socials: { instagram: 'gfg_pccoe', linkedin: 'gfg-pccoe' },
    isJoined: false,
  },
  {
    id: 'c5',
    clubtitle: 'AIMSA',
    clubusername: 'aimsa',
    category: 'Technical',
    description: 'Artificial Intelligence & Machine Learning Student Association.',
    logo: '/aimsa_fza2sz.png',
    coverImage: '/b5_f5yt3v.png',
    membersCount: 310,
    followersCount: 880,
    lead: 'Rohan Deshmukh',
    email: 'aimsa@pccoepune.org',
    socials: { instagram: 'aimsa_pccoe', linkedin: 'aimsa-pccoe' },
    isJoined: false,
  },
  {
    id: 'c6',
    clubtitle: 'IOT & Robotics Club',
    clubusername: 'iotclub',
    category: 'Technical',
    description: 'Hardware, Embedded Systems, Robotics, and Internet of Things research wing.',
    logo: '/iotclub_jkzjbs.png',
    coverImage: '/b6_snjcyi.png',
    membersCount: 280,
    followersCount: 760,
    lead: 'Tanmay Kulkarni',
    email: 'iot@pccoepune.org',
    socials: { instagram: 'iot_pccoe', linkedin: 'iot-pccoe' },
    isJoined: false,
  },
  {
    id: 'c7',
    clubtitle: 'LFDT - Leaders for Tomorrow',
    clubusername: 'lfdt',
    category: 'Social',
    description: 'Leadership, entrepreneurship, personality development, and campus governance.',
    logo: '/lfdt_rueakn.png',
    coverImage: '/b7_ii8wsp.png',
    membersCount: 340,
    followersCount: 910,
    lead: 'Siddharth Patil',
    email: 'lfdt@pccoepune.org',
    socials: { instagram: 'lfdt_pccoe' },
    isJoined: true,
  },
  {
    id: 'c8',
    clubtitle: 'Art Circle PCCOE',
    clubusername: 'artcircle',
    category: 'Cultural',
    description: 'Official theatre, music, dance, visual arts, and literary club of PCCOE.',
    logo: '/artcircle_ubeulk.png',
    coverImage: '/b8_cvne6f.png',
    membersCount: 450,
    followersCount: 2100,
    lead: 'Pooja Iyer',
    email: 'artcircle@pccoepune.org',
    socials: { instagram: 'artcircle_pccoe' },
    isJoined: false,
  },
  {
    id: 'c9',
    clubtitle: 'NSS PCCOE',
    clubusername: 'nss',
    category: 'Social',
    description: 'National Service Scheme - Social service, blood donation camps, and rural upliftment.',
    logo: '/nss_zl4tv7.png',
    coverImage: '/b9_oqyqpu.png',
    membersCount: 500,
    followersCount: 1300,
    lead: 'Amit Shinde',
    email: 'nss@pccoepune.org',
    socials: { instagram: 'nss_pccoe' },
    isJoined: false,
  },
  {
    id: 'c10',
    clubtitle: 'ISR - Institute Social Responsibility',
    clubusername: 'isr',
    category: 'Social',
    description: 'Campus sustainability, clean energy drives, and community education programs.',
    logo: '/isr_ms6a3y.png',
    coverImage: '/b10_ytloej.png',
    membersCount: 260,
    followersCount: 670,
    lead: 'Snehal More',
    email: 'isr@pccoepune.org',
    socials: { instagram: 'isr_pccoe' },
    isJoined: false,
  },
];

export const INITIAL_POSTS = [
  {
    id: 'post_1',
    author: {
      name: 'Chirag Ferwani',
      username: 'chirag',
      avatar: '/user1_ghlxbj.jpg',
      dept: 'Computer Engineering',
      year: 'Final Year',
      badge: 'Cohort Core',
    },
    clubusername: 'owasp',
    communityTitle: 'OWASP Student Chapter',
    content: '🚨 Hackathon Alert! OWASP PCCOE is proud to announce "CyberSprint 2026". 24-hour CTF and Web App Pen-testing challenge with cash prizes worth ₹50,000! Registrations open on Cohort now. Check the communities tab to sign up!',
    image: '/b1_moeeg9.png',
    likesCount: 84,
    isLiked: false,
    repliesCount: 16,
    replies: [
      { id: 'r1', author: 'Neha Joshi', text: 'Can 2nd year students participate as well?', time: '2026-08-18T10:30:00Z', avatar: '/user2_oss1xv.jpg' },
      { id: 'r2', author: 'Chirag Ferwani', text: 'Yes, open for all branches and all academic years!', time: '2026-08-18T10:45:00Z', avatar: '/user1_ghlxbj.jpg' },
    ],
    tags: ['hackathon', 'cybersecurity', 'pccoe'],
    created_at: '2026-08-18T09:15:00Z',
  },
  {
    id: 'post_2',
    author: {
      name: 'Yashvardhan Borude',
      username: 'yashvardhan',
      avatar: '/user3_jasy6u.jpg',
      dept: 'Information Technology',
      year: 'Third Year',
      badge: 'GDGC Lead',
    },
    clubusername: 'gdgc',
    communityTitle: 'GDGC PCCOE',
    content: '🚀 Google Solution Challenge Info-Session is happening this Friday at 4 PM in Auditorium 2 (Mech Building, 4th Floor). Learn how to build for UN Sustainable Goals using Flutter, Gemini & Firebase.',
    image: '/b2_bh32na.png',
    likesCount: 67,
    isLiked: true,
    repliesCount: 8,
    replies: [
      { id: 'r3', author: 'Aditya Sharma', text: 'Looking forward to it! Bringing our entire team.', time: '2026-08-18T11:00:00Z', avatar: '/user4_luy79y.jpg' },
    ],
    tags: ['gdgc', 'google', 'solutionchallenge'],
    created_at: '2026-08-18T08:00:00Z',
  },
  {
    id: 'post_3',
    author: {
      name: 'Pooja Iyer',
      username: 'pooja_iyer',
      avatar: '/user2_oss1xv.jpg',
      dept: 'Electronics & Telecommunication',
      year: 'Final Year',
      badge: 'Cultural Sec',
    },
    clubusername: 'artcircle',
    communityTitle: 'Art Circle PCCOE',
    content: '🎭 Auditions for Purushottam Karandak 2026 are scheduled for this Saturday. Acting, Scriptwriting, Backstage, and Sound Design roles available. Express yourself on the grandest stage!',
    image: '/b8_cvne6f.png',
    likesCount: 112,
    isLiked: false,
    repliesCount: 22,
    replies: [],
    tags: ['artcircle', 'theatre', 'karandak'],
    created_at: '2026-08-17T18:30:00Z',
  },
  {
    id: 'post_4',
    author: {
      name: 'Tanmay Kulkarni',
      username: 'tanmay_k',
      avatar: '/user4_luy79y.jpg',
      dept: 'Mechanical Engineering',
      year: 'Final Year',
      badge: 'Robotics Lead',
    },
    clubusername: 'iotclub',
    communityTitle: 'IOT & Robotics Club',
    content: '🤖 Testing our new Autonomous Guided Vehicle (AGV) prototype in the Central Workshop today. Sensor fusion algorithm achieved 99.2% path accuracy on campus hallways.',
    image: '/b6_snjcyi.png',
    likesCount: 53,
    isLiked: false,
    repliesCount: 5,
    replies: [],
    tags: ['robotics', 'iot', 'engineering'],
    created_at: '2026-08-17T14:10:00Z',
  },
];

export const INITIAL_XD_POSTS = [
  {
    id: 'xd_1',
    content: 'Pro tip for 2nd years: The Central Library 3rd floor quiet zone has the coldest AC and fastest Wi-Fi on campus during exam prep weeks.',
    tag: '#tips',
    upvotes: 94,
    replies: 12,
    time: '2 hours ago',
  },
  {
    id: 'xd_2',
    content: 'The Dosa corner at PCCOE Canteen now serves Schezwan Cheese Masala Dosa and it is honestly the best budget meal on campus.',
    tag: '#canteen',
    upvotes: 142,
    replies: 28,
    time: '4 hours ago',
  },
  {
    id: 'xd_3',
    content: 'Are mock placements for 2027 batch starting from next month? Any recommendations for OS and DBMS interview prep?',
    tag: '#placements',
    upvotes: 68,
    replies: 19,
    time: '6 hours ago',
  },
  {
    id: 'xd_4',
    content: 'In-sem exam schedule just dropped on the notice board. Only 3 days between Unit 1 and Unit 2 tests. Time to grind.',
    tag: '#exams',
    upvotes: 83,
    replies: 15,
    time: '1 day ago',
  },
  {
    id: 'xd_5',
    content: 'Big shoutout to the faculty mentors in the Computer Lab 4 for staying back till 7 PM to help us debug our Capstone Project.',
    tag: '#professors',
    upvotes: 120,
    replies: 9,
    time: '2 days ago',
  },
];

export const INITIAL_CALENDAR_EVENTS = [
  {
    id: 'ev_1',
    title: 'In-Semester Examination (SPPU / Autonomous)',
    date: '2026-08-25',
    category: 'Exams',
    description: 'Unit 1 & Unit 2 In-Sem tests across all engineering departments.',
    location: 'Assigned Classrooms',
    time: '10:00 AM - 01:00 PM',
  },
  {
    id: 'ev_2',
    title: 'OWASP CyberSprint CTF Hackathon',
    date: '2026-08-28',
    category: 'Hackathons',
    description: '24-hour ethical hacking and web application security competition.',
    location: 'Computer Lab 1 & 2',
    time: '09:00 AM onwards',
  },
  {
    id: 'ev_3',
    title: 'Final Year Capstone Project Milestone 1',
    date: '2026-09-05',
    category: 'Submissions',
    description: 'Synopsis and SRS submission to departmental review committee.',
    location: 'Department Seminar Halls',
    time: '05:00 PM Deadline',
  },
  {
    id: 'ev_4',
    title: 'Ganesh Chaturthi Campus Festival',
    date: '2026-09-14',
    category: 'Holidays',
    description: 'College Holiday - Campus Cultural Celebration.',
    location: 'PCCOE Campus',
    time: 'All Day',
  },
  {
    id: 'ev_5',
    title: 'Kshitij 2026 - Annual Tech & Cultural Fest',
    date: '2026-09-22',
    category: 'Fest',
    description: 'Largest student festival in PCMC region featuring 40+ events.',
    location: 'PCCOE Grounds & Auditorium',
    time: '3-Day Gala',
  },
];

export const INITIAL_HEADSUP_NOTICES = [
  {
    id: 'h1',
    title: 'Exam Hall Ticket Distribution for Autumn 2026',
    department: 'Examination Cell',
    urgency: 'High',
    date: '18 Aug 2026',
    isPinned: true,
    content: 'Students are requested to collect their endorsed hall tickets from respective department academic coordinators before 22nd August.',
  },
  {
    id: 'h2',
    title: 'Campus Placement Drive: Deutsche Bank & Mastercard',
    department: 'Training & Placement Cell (T&P)',
    urgency: 'High',
    date: '17 Aug 2026',
    isPinned: true,
    content: 'Eligible 2027 batch candidates with 7.5+ CGPA must complete profile verification on the T&P portal by tomorrow 6 PM.',
  },
  {
    id: 'h3',
    title: 'PCCOE Central Library Extended Study Hours',
    department: 'Central Library',
    urgency: 'Normal',
    date: '15 Aug 2026',
    isPinned: false,
    content: 'Reading halls on the 2nd and 3rd floors will remain open till 11:00 PM throughout the examination month.',
  },
  {
    id: 'h4',
    title: 'Smart India Hackathon (SIH) Internal Campus Screening',
    department: 'Research & Innovation Wing',
    urgency: 'Normal',
    date: '12 Aug 2026',
    isPinned: false,
    content: 'Top 30 team ideas will be nominated for the National SIH 2026 Grand Finale. Submit PPT slides by 25th August.',
  },
];

export const INITIAL_USERS = [
  {
    id: 'u1',
    name: 'Chirag Ferwani',
    username: 'chirag',
    email: 'chiragferwani@gmail.com',
    dept: 'Computer Engineering',
    year: 'Final Year',
    avatar: '/user1_ghlxbj.jpg',
    role: 'Admin',
    prn: '121B1B045',
    prScore: 980,
    bio: 'Full Stack Architect & Security Enthusiast. Creator of Cohort PCCOE. Lead at OWASP PCCOE.',
    skills: ['React', 'Node.js', 'PostgreSQL', 'Supabase', 'Cybersecurity', 'Cloud Architecture'],
    achievements: [
      { title: 'Winner - National Smart India Hackathon', org: 'Govt of India', year: '2025' },
      { title: 'Secured 1st Place - CyberSprint CTF', org: 'OWASP Pune', year: '2025' },
      { title: 'Published IEEE Paper on Realtime Encryption', org: 'IEEE Xplore', year: '2026' },
    ],
    followers: 480,
    following: 120,
    isFollowing: false,
  },
  {
    id: 'u2',
    name: 'Yashvardhan Borude',
    username: 'yashvardhan',
    email: 'yashvardhan.borude@pccoepune.org',
    dept: 'Information Technology',
    year: 'Third Year',
    avatar: '/user3_jasy6u.jpg',
    role: 'Student',
    prn: '122B1B102',
    prScore: 920,
    bio: 'Software engineer building modern web experiences & AI systems. GDGC Lead.',
    skills: ['TypeScript', 'React', 'Python', 'Tailwind CSS', 'Vite', 'Machine Learning'],
    achievements: [
      { title: 'GDGC Solution Challenge Global Top 100', org: 'Google Developers', year: '2025' },
      { title: 'HackPCCOE Grand Finalist', org: 'PCCOE Pune', year: '2025' },
    ],
    followers: 350,
    following: 140,
    isFollowing: true,
  },
  {
    id: 'u3',
    name: 'Pooja Iyer',
    username: 'pooja_iyer',
    email: 'pooja.iyer@pccoepune.org',
    dept: 'Electronics & Telecommunication',
    year: 'Final Year',
    avatar: '/user2_oss1xv.jpg',
    role: 'Student',
    prn: '121B1B088',
    prScore: 890,
    bio: 'Electronics enthusiast, Theatre artist at Art Circle PCCOE, Karandak winner.',
    skills: ['VLSI', 'Embedded Systems', 'Theatre Direction', 'Public Speaking'],
    achievements: [
      { title: 'Best Actor - Firodiya Karandak 2025', org: 'Firodiya Pune', year: '2025' },
    ],
    followers: 620,
    following: 210,
    isFollowing: false,
  },
  {
    id: 'u4',
    name: 'Aditya Sharma',
    username: 'aditya_s',
    email: 'aditya.sharma@pccoepune.org',
    dept: 'Computer Engineering',
    year: 'Final Year',
    avatar: '/user4_luy79y.jpg',
    role: 'Student',
    prn: '121B1B012',
    prScore: 870,
    bio: 'Competitive Programmer | Candidate Master on Codeforces | ACM Lead.',
    skills: ['C++', 'Algorithms', 'Distributed Systems', 'System Design'],
    achievements: [
      { title: 'ACM ICPC Regionalist', org: 'ICPC Global', year: '2025' },
    ],
    followers: 290,
    following: 85,
    isFollowing: false,
  },
];

export const INITIAL_MESSAGES = [
  {
    id: 'm1',
    channelId: 'owasp-core',
    sender: 'chirag',
    senderName: 'Chirag Ferwani',
    avatar: '/user1_ghlxbj.jpg',
    text: 'Hey team, the CyberSprint problem statements are finalized. Ready for test rounds?',
    timestamp: '10:15 AM',
  },
  {
    id: 'm2',
    channelId: 'owasp-core',
    sender: 'yashvardhan',
    senderName: 'Yashvardhan Borude',
    avatar: '/user3_jasy6u.jpg',
    text: 'Yes! Automated grading container is up and running on AWS.',
    timestamp: '10:18 AM',
  },
  {
    id: 'm3',
    channelId: 'owasp-core',
    sender: 'chirag',
    senderName: 'Chirag Ferwani',
    avatar: '/user1_ghlxbj.jpg',
    text: 'Awesome. I will push the announcements to the c/owasp community channel now.',
    timestamp: '10:20 AM',
  },
];

export const CAMPUS_LOCATIONS = [
  {
    id: 'loc_comp_it',
    name: 'Computer & IT Engineering Building',
    code: 'B-Block',
    floors: 6,
    facilities: ['Computer Lab 1 to 8', 'Department Library', 'Server Room', 'HOD Office (2nd Floor)', 'Seminar Hall'],
    coordinates: { x: 38, y: 42 },
    category: 'Academic',
  },
  {
    id: 'loc_mech',
    name: 'Mechanical & Civil Engineering Building',
    code: 'A-Block',
    floors: 5,
    facilities: ['Auditorium 1 & 2', 'CAD/CAM Lab', 'Fluid Mechanics Lab', 'Dean Academics Office', 'Board Room'],
    coordinates: { x: 62, y: 35 },
    category: 'Academic',
  },
  {
    id: 'loc_admin',
    name: 'Administrative Building & Central Office',
    code: 'Admin-Block',
    floors: 4,
    facilities: ['Principal Office', 'Registrar & Student Section', 'Accounts Cell', 'Conference Room', 'Examination Cell'],
    coordinates: { x: 50, y: 22 },
    category: 'Admin',
  },
  {
    id: 'loc_library',
    name: 'Central Library & Reading Hall',
    code: 'Library-Block',
    floors: 3,
    facilities: ['Digital Library', 'Quiet Reading Hall', 'Book Lending Section', 'Periodicals & Research Section'],
    coordinates: { x: 25, y: 55 },
    category: 'Facility',
  },
  {
    id: 'loc_canteen',
    name: 'PCCOE Food Court & Canteen',
    code: 'Cafeteria',
    floors: 2,
    facilities: ['Main Dining Hall', 'Snack Bar', 'Juice Center', 'Outdoor Garden Seating'],
    coordinates: { x: 75, y: 65 },
    category: 'Facility',
  },
  {
    id: 'loc_workshop',
    name: 'Central Mechanical Workshop & Innovation Lab',
    code: 'Workshop',
    floors: 1,
    facilities: ['CNC Machining Center', 'Welding & Fitting Section', 'Robotics Testing Arena', '3D Printing FabLab'],
    coordinates: { x: 70, y: 20 },
    category: 'Facility',
  },
  {
    id: 'loc_sports',
    name: 'Sports Complex & Football Ground',
    code: 'Ground',
    floors: 1,
    facilities: ['Basketball Court', 'Cricket Nets', 'Gymnasium', 'Badminton Court'],
    coordinates: { x: 20, y: 80 },
    category: 'Sports',
  },
];
